'use client'
import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { createClient } from '@/utils/supabase/client'
import { Sparkles, ArrowUp, Briefcase, Zap, Star } from 'lucide-react'
import { showToast } from '@/components/ui'

const supabase = createClient()

export default function PlannerPage() {
  const router = useRouter()
  const [idea, setIdea] = useState('')
  const [experience, setExperience] = useState('intermediate')
  const [preference, setPreference] = useState('free')
  const [loading, setLoading] = useState(false)

  async function handleGenerate(e: React.FormEvent) {
    e.preventDefault()
    if (!idea.trim()) return
    setLoading(true)

    try {
      // Call AI plan API
      const res = await fetch('/api/ai/plan', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        // Passing 'free' or 'premium' via the budget field for the backend to understand
        body: JSON.stringify({ idea, experience, budget: preference, platform: 'web' })
      })
      const plan = await res.json()
      if (plan.error) throw new Error(plan.error)

      // Get current user
      const { data: { user } } = await supabase.auth.getUser()
      if (!user) { router.push('/login'); return }

      // Save project to Supabase
      const { data: project, error: projErr } = await supabase
        .from('projects')
        .insert({
          user_id: user.id,
          name: idea.slice(0, 60),
          idea: idea,
          platform: 'web',
          experience: experience,
          budget: preference,
          stack: plan.stack,
          estimated_hours: plan.estimated_hours,
          complexity: plan.complexity,
          status: 'active',
        })
        .select().single()

      if (projErr) throw new Error(projErr.message)

      // Save features generated by AI (using the default features creation method we had, or wait, the AI plan doesn't generate features. Actually the AI plan generates the tech stack and phases. The features are currently hardcoded or added in the next step. Let's just go to the next step where they are auto-generated).
      
      // Save phases
      await supabase.from('phases').insert(
        plan.phases.map((p: any) => ({
          project_id: project.id,
          phase_number: p.phase_number,
          name: p.name, tool: p.tool,
          duration: p.duration, status: 'pending'
        }))
      )

      showToast('✓ Build plan generated! Moving to features...')
      router.push(`/planner/features?project=${project.id}`)

    } catch (err: any) {
      showToast(err.message || 'Something went wrong')
      setLoading(false)
    }
  }

  return (
    <div style={{
      minHeight: 'calc(100vh - 58px)',
      background: 'radial-gradient(circle at 50% -20%, rgba(244,63,94,0.15) 0%, rgba(66,127,131,.1) 40%, #eef3f4 80%)',
      display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center',
      padding: '40px 20px', position: 'relative'
    }}>
      <div style={{ textAlign: 'center', marginBottom: '40px', animation: 'fadeIn 0.5s ease' }}>
        <h1 style={{ fontFamily: 'Syne, sans-serif', fontSize: 'clamp(32px, 5vw, 48px)', fontWeight: 800, color: '#fff', marginBottom: '16px' }}>
          Let&rsquo;s build something.
        </h1>
        <p style={{ color: '#607276', fontSize: '16px' }}>
          Describe your idea. Torus AI will design the perfect architecture.
        </p>
      </div>

      <form onSubmit={handleGenerate} style={{ width: '100%', maxWidth: '800px', animation: 'slideUp 0.5s ease 0.1s both' }}>
        <div style={{
          background: 'rgba(255,255,255,.54)', border: '1px solid rgba(38,69,72,.14)',
          borderRadius: '24px', padding: '24px', boxShadow: '0 20px 40px rgba(0,0,0,0.4), 0 0 0 1px rgba(66,127,131,.1)'
        }}>
          <textarea
            value={idea}
            onChange={e => setIdea(e.target.value)}
            placeholder="Ask Torus AI to build an internal tool that..."
            style={{
              width: '100%', minHeight: '120px', background: 'transparent', border: 'none',
              color: '#172326', fontSize: '18px', outline: 'none', resize: 'none',
              fontFamily: 'DM Sans, sans-serif', lineHeight: '1.5', marginBottom: '20px'
            }}
            autoFocus
          />
          
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', borderTop: '1px solid rgba(38,69,72,.1)', paddingTop: '20px', flexWrap: 'wrap', gap: '16px' }}>
            
            {/* Options */}
            <div style={{ display: 'flex', gap: '20px' }}>
              <div>
                <label style={{ display: 'block', fontSize: '11px', color: '#8a9a9d', fontFamily: 'DM Mono, monospace', textTransform: 'uppercase', marginBottom: '8px' }}>Experience Level</label>
                <div style={{ display: 'flex', gap: '6px', background: 'rgba(255,255,255,.02)', padding: '4px', borderRadius: '10px' }}>
                  {['beginner', 'intermediate', 'advanced'].map(lvl => (
                    <button key={lvl} type="button" onClick={() => setExperience(lvl)} style={{
                      padding: '6px 12px', background: experience === lvl ? 'rgba(38,69,72,.12)' : 'transparent',
                      border: 'none', borderRadius: '6px', color: experience === lvl ? '#fff' : '#607276',
                      fontSize: '12px', cursor: 'pointer', transition: 'all 0.2s', textTransform: 'capitalize'
                    }}>
                      {lvl}
                    </button>
                  ))}
                </div>
              </div>

              <div>
                <label style={{ display: 'block', fontSize: '11px', color: '#8a9a9d', fontFamily: 'DM Mono, monospace', textTransform: 'uppercase', marginBottom: '8px' }}>Tool Preference</label>
                <div style={{ display: 'flex', gap: '6px', background: 'rgba(255,255,255,.02)', padding: '4px', borderRadius: '10px' }}>
                  <button type="button" onClick={() => setPreference('free')} style={{
                    padding: '6px 12px', background: preference === 'free' ? 'rgba(16,185,129,.15)' : 'transparent',
                    border: 'none', borderRadius: '6px', color: preference === 'free' ? '#10b981' : '#607276',
                    fontSize: '12px', cursor: 'pointer', transition: 'all 0.2s', display: 'flex', alignItems: 'center', gap: '4px'
                  }}>
                    <Zap size={12} /> Free AI Tools
                  </button>
                  <button type="button" onClick={() => setPreference('premium')} style={{
                    padding: '6px 12px', background: preference === 'premium' ? 'rgba(245,158,11,.15)' : 'transparent',
                    border: 'none', borderRadius: '6px', color: preference === 'premium' ? '#f59e0b' : '#607276',
                    fontSize: '12px', cursor: 'pointer', transition: 'all 0.2s', display: 'flex', alignItems: 'center', gap: '4px'
                  }}>
                    <Star size={12} /> Premium
                  </button>
                </div>
              </div>
            </div>

            {/* Submit */}
            <button type="submit" disabled={loading || !idea.trim()} style={{
              width: '44px', height: '44px', background: loading ? '#4a2080' : '#427f83',
              border: 'none', borderRadius: '50%', color: '#fff', display: 'flex', alignItems: 'center', justifyContent: 'center',
              cursor: loading || !idea.trim() ? 'not-allowed' : 'pointer', opacity: !idea.trim() ? 0.5 : 1,
              transition: 'all 0.2s', boxShadow: loading ? 'none' : '0 4px 12px rgba(66,127,131,.28)'
            }}>
              {loading ? (
                <div style={{ width: '16px', height: '16px', border: '2px solid rgba(255,255,255,.3)', borderTopColor: '#fff', borderRadius: '50%', animation: 'spin 0.7s linear infinite' }} />
              ) : (
                <ArrowUp size={20} />
              )}
            </button>
          </div>
        </div>
      </form>

      <div style={{ marginTop: '40px', display: 'flex', gap: '16px', color: '#8a9a9d', fontSize: '12px', fontFamily: 'DM Mono, monospace', animation: 'fadeIn 0.5s ease 0.3s both' }}>
        <span style={{ display: 'flex', alignItems: 'center', gap: '6px' }}><Sparkles size={14} /> AI Powered Planning</span>
        <span style={{ display: 'flex', alignItems: 'center', gap: '6px' }}><Briefcase size={14} /> Full Stack Architecture</span>
      </div>

      <style>{`
        @keyframes spin { to { transform: rotate(360deg); } }
        @keyframes fadeIn { from { opacity: 0; } to { opacity: 1; } }
        @keyframes slideUp { from { opacity: 0; transform: translateY(20px); } to { opacity: 1; transform: translateY(0); } }
      `}</style>
    </div>
  )
}
